language: php

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER: weak

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  allow_failures:
    - env: SYMFONY_VERSION='3.0.*@dev'
  include:
    - php: 5.6
      env: SYMFONY_VERSION='3.0.*@dev'

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi
